-- Creating a new Column for normalized values

ALTER Table manufacturers
ADD COLUMN name_normalized VARCHAR(255);

-- Modifying the datatype to longtext
ALTER TABLE manufacturers modify column name_normalized longtext;

WITH normalized_name AS (
	SELECT *,
		CASE
		WHEN name LIKE '%oculus%' THEN 'OCULUS'
WHEN name LIKE '%A-DEC%' THEN 'A-DEC'
WHEN name LIKE '%A.M.I%' THEN 'A.M.I'
WHEN name LIKE '%A&D%' THEN 'A&D'
WHEN name LIKE '%Abc%' THEN 'Abc'
WHEN name LIKE '%Abiomed%' THEN 'Abiomed'
WHEN name LIKE '%Accuray%' THEN 'Accuray'
WHEN name LIKE '%Ace Medical%' THEN 'Ace Medical'
WHEN name LIKE '%Acutronic%' THEN 'Acutronic'
WHEN name LIKE '%Aerogen%' THEN 'Aerogen'
WHEN name LIKE '%Airway%' THEN 'Airway'
WHEN name LIKE '%Akin%' THEN 'Akin'
WHEN name LIKE '%Aks%' THEN 'Aks'
WHEN name LIKE '%Allegra%' THEN 'Allegra'
WHEN name LIKE '%Alphatec%' THEN 'Alphatec'
WHEN name LIKE '%Anatomic%' THEN 'Anatomic'
WHEN name LIKE '%AngioDynamics%' THEN 'AngioDynamics'
WHEN name LIKE '%Ansell%' THEN 'Ansell'
WHEN name LIKE '%Apax%' THEN 'Apax'
WHEN name LIKE '%Apollo%' THEN 'Apollo'
WHEN name LIKE '%Applied Medical%' THEN 'Applied Medical'
WHEN name LIKE '%Arkray%' THEN 'Arkray'
WHEN name LIKE '%Akin%' THEN 'Akin'
WHEN name LIKE '%Armstrong%' THEN 'Armstrong'
WHEN name LIKE '%Arthrex%' THEN 'Arthrex'
WHEN name LIKE '%Asahi%' THEN 'Asahi'
WHEN name LIKE '%Aspect Medical Systems%' THEN 'Aspect Medical Systems'
WHEN name LIKE '%Atricure%' THEN 'Atricure'
WHEN name LIKE '%Auris Health%' THEN 'Auris Health'
WHEN name LIKE '%Avanos Medical%' THEN 'Avanos Medical'
WHEN name LIKE '%Barrfab%' THEN 'Barrfab'
WHEN name LIKE '%BBI%' THEN 'BBI'
WHEN name LIKE '%Becton, Dickinson and Company%' THEN 'Becton, Dickinson and Company'
WHEN name LIKE '%Belmont Instrument%' THEN 'Belmont Instrument'
WHEN name LIKE '%Berkshire Hathaway%' THEN 'Berkshire Hathaway'
WHEN name LIKE '%Bio-Rad Laboratories%' THEN 'Bio-Rad Laboratories'
WHEN name LIKE '%Biocardia%' THEN 'Biocardia'
WHEN name LIKE '%Biolytical Laboratories%' THEN 'Biolytical Laboratories'
WHEN name LIKE '%Biomerica%' THEN 'Biomerica'
WHEN name LIKE '%Bionet%' THEN 'Bionet'
WHEN name LIKE '%Biosensors International Group%' THEN 'Biosensors International Group'
WHEN name LIKE '%Biosynex%' THEN 'Biosynex'
WHEN name LIKE '%Bioteck%' THEN 'Bioteck'
WHEN name LIKE '%Cambridge Endoscopic%' THEN 'Cambridge Endoscopic'
WHEN name LIKE '%Cantel Medical%' THEN 'Cantel Medical'
WHEN name LIKE '%Cantel Medical%' THEN 'Cantel Medical'
WHEN name LIKE '%Cardia%' THEN 'Cardia'
WHEN name LIKE '%Cardiac Science%' THEN 'Cardiac Science'
WHEN name LIKE '%Cardiovascular Systems%' THEN 'Cardiovascular Systems'
WHEN name LIKE '%Cas Medical Systems%' THEN 'Cas Medical Systems'
WHEN name LIKE '%Cellnovo Group%' THEN 'Cellnovo Group'
WHEN name LIKE '%Ceragem%' THEN 'Ceragem'
WHEN name LIKE '%Change Healthcare%' THEN 'Change Healthcare'
WHEN name LIKE '%Changzhou%' THEN 'Changzhou'
WHEN name LIKE '%Charder Electronic%' THEN 'Charder Electronic'
WHEN name LIKE '%Chart Industries%' THEN 'Chart Industries'
WHEN name LIKE '%China Resources Pharmaceutical Group%' THEN 'China Resources Pharmaceutical Group'
WHEN name LIKE '%Cidron%' THEN 'Cidron'
WHEN name LIKE '%CoBe%' THEN 'CoBe'
WHEN name LIKE '%Codan%' THEN 'Codan'
WHEN name LIKE '%Concert Medical%' THEN 'Concert Medical'
WHEN name LIKE '%Confluent Medical Technologies%' THEN 'Confluent Medical Technologies'
WHEN name LIKE '%Conformis%' THEN 'Conformis'
WHEN name LIKE '%Corvia Medical%' THEN 'Corvia Medical'
WHEN name LIKE '%Cryolife%' THEN 'Cryolife'
WHEN name LIKE '%Cu Medical Systems%' THEN 'CU Medical Systems'
WHEN name LIKE '%Custom HealthCare%' THEN 'Custom HealthCare'
WHEN name LIKE '%Cutera%' THEN 'Cutera'
WHEN name LIKE '%CytoSorbents%' THEN 'CytoSorbents'
WHEN name LIKE '%Demophorius%' THEN 'Demophorius'
WHEN name LIKE '%Descram%' THEN 'Descram'
WHEN name LIKE '%Device Technologies Australia%' THEN 'Device Technologies Australia'
WHEN name LIKE '%Dextera Surgical%' THEN 'Dextera Surgical'
WHEN name LIKE '%DFS - DIAMON%' THEN 'DFS - DIAMON'
WHEN name LIKE '%Diagmed Healthcare%' THEN 'Diagmed Healthcare'
WHEN name LIKE '%Dialab%' THEN 'Dialab'
WHEN name LIKE '%Diaxonhit%' THEN 'Diaxonhit'
WHEN name LIKE '%Dr. Arabin%' THEN 'Dr. Arabin'
WHEN name LIKE '%Dr. Schumacher%' THEN 'Dr. Schumacher'
WHEN name LIKE '%DXC Technology%' THEN 'DXC Technology'
WHEN name LIKE '%Dynek%' THEN 'Dynek'
WHEN name LIKE '%Ecolab%' THEN 'Ecolab'
WHEN name LIKE '%Edan Instruments%' THEN 'Edan Instruments'
WHEN name LIKE '%Eizo Corporation%' THEN 'Eizo Corporation'
WHEN name LIKE '%Elcam Medical%' THEN 'Elcam Medical'
WHEN name LIKE '%Ellex Medical Lasers%' THEN 'Ellex Medical Lasers'
WHEN name LIKE '%Endologix%' THEN 'Endologix'
WHEN name LIKE '%Engineered Medical Systems%' THEN 'Engineered Medical Systems'
WHEN name LIKE '%Endologix%' THEN 'Endologix'
WHEN name LIKE '%EPflex Feinwerktechnik%' THEN 'EPflex Feinwerktechnik'
WHEN name LIKE '%Eurazeo%' THEN 'Eurazeo'
WHEN name LIKE '%Euromi%' THEN 'Euromi'
WHEN name LIKE '%Exactech%' THEN 'Exactech'
WHEN name LIKE '%FEG Textiltechnik Forschungs%' THEN 'FEG Textiltechnik Forschungs'
WHEN name LIKE '%Financiere%' THEN 'Financiere'
WHEN name LIKE '%Fisher & Paykel Healthcare%' THEN 'Fisher & Paykel Healthcare'
WHEN name LIKE '%Fluoron%' THEN 'Fluoron'
WHEN name LIKE '%Focus Medical%' THEN 'Focus Medical'
WHEN name LIKE '%Fresenius SE%' THEN 'Fresenius SE'
WHEN name LIKE '%Fritz%' THEN 'Fritz'
WHEN name LIKE '%Fukuda Denshi%' THEN 'Fukuda Denshi'
WHEN name LIKE '%Gabmed Produtos%' THEN 'Gabmed Produtos'
WHEN name LIKE '%General Electric%' THEN 'General Electric'
WHEN name LIKE '%Genesis%' THEN 'Genesis'
WHEN name LIKE '%Genicon%' THEN 'Genicon'
WHEN name LIKE '%Golden Technologies%' THEN 'Golden Technologies'
WHEN name LIKE '%Green Cross%' THEN 'Green Cross'
WHEN name LIKE '%Guangzhou Wondfo Biotech%' THEN 'Guangzhou Wondfo Biotech'
WHEN name LIKE '%Guldmann%' THEN 'Guldmann'
WHEN name LIKE '%Halyard Health%' THEN 'Halyard Health'
WHEN name LIKE '%Hangzhou Ags Medtech%' THEN 'Hangzhou Ags Medtech'
WHEN name LIKE '%Hangzhou Biotest Biotech%' THEN 'Hangzhou Biotest Biotech'
WHEN name LIKE '%Heart Sync%' THEN 'Heart Sync'
WHEN name LIKE '%Hengan%' THEN 'Hengan'
WHEN name LIKE '%Henry Schein%' THEN 'Henry Schein'
WHEN name LIKE '%Heritage Worldwide%' THEN 'Heritage Worldwide'
WHEN name LIKE '%Hologic%' THEN 'Hologic'
WHEN name LIKE '%HOYA Corp%' THEN 'HOYA Corp'
WHEN name LIKE '%HS Hospital Service%' THEN 'HS Hospital Service'
WHEN name LIKE '%Icu Medical%' THEN 'Icu Medical'
WHEN name LIKE '%Idoman%' THEN 'Idoman'
WHEN name LIKE '%Implantech Associates%' THEN 'Implantech Associates'
WHEN name LIKE '%Integra Neurosciences%' THEN 'Integra Neurosciences'
WHEN name LIKE '%International Biophysics Corp%' THEN 'International Biophysics Corp'
WHEN name LIKE '%Intrasense%' THEN 'Intrasense'
WHEN name LIKE '%Intuitive Surgical%' THEN 'Intuitive Surgical'
WHEN name LIKE '%Ion Beam Application%' THEN 'Ion Beam Application'
WHEN name LIKE '%Itd Gmbh%' THEN 'Itd Gmbh'
WHEN name LIKE '%Ivoclar Vivadent%' THEN 'Ivoclar Vivadent'
WHEN name LIKE '%Jiangsu Kangjian%' THEN 'Jiangsu Kangjian'
WHEN name LIKE '%Jms Co%' THEN 'Jms Co'
WHEN name LIKE '%Johnson & Johnson%' THEN 'Johnson & Johnson'
WHEN name LIKE '%Juniper Holdings%' THEN 'Juniper Holdings'
WHEN name LIKE '%Karl Beese%' THEN 'Karl Beese'
WHEN name LIKE '%Karl Storz%' THEN 'Karl Storz'
WHEN name LIKE '%Keystone%' THEN 'Keystone'
WHEN name LIKE '%Kkr & Co%' THEN 'Kkr & Co'
WHEN name LIKE '%Kobayashi Pharmaceutical%' THEN 'Kobayashi Pharmaceutical'
WHEN name LIKE '%Konica Minolta%' THEN 'Konica Minolta'
WHEN name LIKE '%Lanai Medical%' THEN 'Lanai Medical'
WHEN name LIKE '%Lemaitre Vascular%' THEN 'Lemaitre Vascular'
WHEN name LIKE '%LifeTech Scientific%' THEN 'LifeTech Scientific'
WHEN name LIKE '%Lifewatch%' THEN 'Lifewatch'
WHEN name LIKE '%Lombard Medical%' THEN 'Lombard Medical'
WHEN name LIKE '%M.A Arain and Brothers%' THEN 'M.A Arain and Brothers'
WHEN name LIKE '%Mammendorfer%' THEN 'Mammendorfer'
WHEN name LIKE '%Masimo%' THEN 'Masimo'
WHEN name LIKE '%Matrix Surgical%' THEN 'Matrix Surgical'
WHEN name LIKE '%Med-El%' THEN 'Med-El Corp'
WHEN name LIKE '%Medacta%' THEN 'Medacta'
WHEN name LIKE '%Medica %' THEN 'Medica Corp'
WHEN name LIKE '%Medical Information Technology%' THEN 'Medical Information Technology'
WHEN name LIKE '%Mediplus Limited%' THEN 'Mediplus Limited'
WHEN name LIKE '%Meditech Systems%' THEN 'Meditech Systems'
WHEN name LIKE '%MedTest Holdings%' THEN 'MedTest Holdings'
WHEN name LIKE '%Membrana%' THEN 'Membrana GMBH'
WHEN name LIKE '%Mercury Enterprises Inc.%' THEN 'Mercury Enterprises Inc.'
WHEN name LIKE '%Merit Medical Systems Inc%' THEN 'Merit Medical Systems Inc'
WHEN name LIKE '%Microbiologics Inc%' THEN 'Microbiologics Inc'
WHEN name LIKE '%Microsoft%' THEN 'Microsoft Corp'
WHEN name LIKE '%Milestone Scientific%' THEN 'Milestone Scientific'
WHEN name LIKE '%Millipore%' THEN 'Millipore'
WHEN name LIKE '%Mitsubishi%' THEN 'Mitsubishi'
WHEN name LIKE '%Mitsui%' THEN 'Mitsui'
WHEN name LIKE '%Mizuho%' THEN 'Mizuho'
WHEN name LIKE '%Moog Inc%' THEN 'Moog Inc'
WHEN name LIKE '%Mortara Instrument, Inc%' THEN 'Mortara Instrument, Inc'
WHEN name LIKE '%Myelotec Inc%' THEN 'Myelotec Inc'
WHEN name LIKE '%New Mountain Capital%' THEN 'New Mountain Capital'
WHEN name LIKE '%Nidek Medical Products%' THEN 'Nidek Medical Products'
WHEN name LIKE '%Nikkiso Co%' THEN 'Nikkiso Co'
WHEN name LIKE '%Nitta Corp%' THEN 'Nitta Corporation'
WHEN name LIKE '%North American Rescue%' THEN 'North American Rescue'
WHEN name LIKE '%Novo Nordisk%' THEN 'Novo Nordisk'
WHEN name LIKE '%Numed%' THEN 'Numed Inc'
WHEN name LIKE '%Oakworks%' THEN 'Oakworks Inc'
WHEN name LIKE '%Orasure Technologies%' THEN 'Orasure Technologies'
WHEN name LIKE '%Ortho Solutions%' THEN 'Ortho Solutions Ltd'
WHEN name LIKE '%Abbot%' THEN 'Abbott'
WHEN name LIKE '%Medtronic%' THEN 'Medtronic'
WHEN name LIKE '%Johnson & Johnson%' THEN 'Johnson & Johnson'
    ELSE name
  END AS normalized_name
FROM manufacturers
)
-- Updating the table with new normalized values
UPDATE manufacturers m
LEFT JOIN normalized_name n
ON m.id = n.id
SET m.name_normalized = n.normalized_name;
